# Add any package you use within your drake plan here.
library(drake)
library(heaven)
library(data.table)
library(readxl)
library(magrittr)
library(purrr)
library(flextable)
library(officer)
library(ggplot2)
